### ISSUE TITLE
Erro ao acessar Anymarket Feed e Anymarket Order

### ISSUE THREAD

**Issue by mferracioli** [AnyMarket/magento2#14]
Ao tentar acessar os itens Order e Feed do menu Anymarket, estoura exceptions nas controllers.

Versão do Magento: 2.4.6
PHP: 8.2.18

```
[2024-06-19T11:53:13.879761+00:00] main.CRITICAL: Exception: Deprecated Functionality: Creation of dynamic property Anymarket\Anymarket\Controller\Adminhtml\anymarketfeed\Index\Interceptor::$resultPageFactory is deprecated in /var/www/camafeo/vendor/anymarket/module-anymarket/Controller/Adminhtml/anymarketfeed/Index.php on line 24 in /var/www/camafeo/vendor/magento/framework/App/ErrorHandler.php:62
Stack trace:
#0 /var/www/camafeo/vendor/anymarket/module-anymarket/Controller/Adminhtml/anymarketfeed/Index.php(24): Magento\Framework\App\ErrorHandler->handler()
#1 /var/www/camafeo/generated/code/Anymarket/Anymarket/Controller/Adminhtml/anymarketfeed/Index/Interceptor.php(14): Anymarket\Anymarket\Controller\Adminhtml\anymarketfeed\Index->__construct()
#2 /var/www/camafeo/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Anymarket\Anymarket\Controller\Adminhtml\anymarketfeed\Index\Interceptor->__construct()
#3 /var/www/camafeo/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#4 /var/www/camafeo/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create()
#5 /var/www/camafeo/vendor/magento/framework/App/ActionFactory.php(44): Magento\Framework\ObjectManager\ObjectManager->create()
#6 /var/www/camafeo/vendor/magento/framework/App/Router/Base.php(306): Magento\Framework\App\ActionFactory->create()
#7 /var/www/camafeo/vendor/magento/framework/App/Router/Base.php(167): Magento\Framework\App\Router\Base->matchAction()
#8 /var/www/camafeo/vendor/magento/framework/App/FrontController.php(144): Magento\Framework\App\Router\Base->match()
#9 /var/www/camafeo/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#10 /var/www/camafeo/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#11 /var/www/camafeo/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#12 /var/www/camafeo/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#13 /var/www/camafeo/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#14 /var/www/camafeo/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#15 /var/www/camafeo/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#16 {main} {"report_id":"7092b428e640ddaea1183f7ca1909ba30b9b97bbbba02534ac69925dbad7570e","exception":"[object] (Exception(code: 0): Deprecated Functionality: Creation of dynamic property Anymarket\\Anymarket\\Controller\\Adminhtml\\anymarketfeed\\Index\\Interceptor::$resultPageFactory is deprecated in /var/www/camafeo/vendor/anymarket/module-anymarket/Controller/Adminhtml/anymarketfeed/Index.php on line 24 at /var/www/camafeo/vendor/magento/framework/App/ErrorHandler.php:62)"} []
```

**Comment by marcelohferreira** [comment]
Realizado a correção dos arquivos para compatibilidade com PHP
